---
abstract: 'General-purpose content-addressed storage (CAS) for Catalyst'
author:
  - 'Henry Van Styn <vanstyn@cpan.org>'
build_requires:
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-SimpleCAS
requires:
  CSS::Simple: 0
  Catalyst::Controller: 0
  Catalyst::Utils: 0
  Data::Dumper: 0
  Digest::SHA1: 0
  Email::MIME: 0
  Email::MIME::CreateHTML: 0
  Email::MIME::CreateHTML::Resolver::LWP: 0
  Encode: 0
  File::MimeInfo::Magic: 0
  HTML::Encoding: 0
  HTML::TokeParser::Simple: 0
  IO::All: 0
  IO::File: 0
  Image::Size: 0
  JSON::DWIW: 0
  MIME::Base64: 0
  Module::Runtime: 0
  Moose: 0
  MooseX::MethodAttributes::Role: 0.29
  Path::Class: 0
  RapidApp::Include: 0
  String::Random: 0
  Try::Tiny: 0
  Types::Standard: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/vanstyn/Catalyst-Controller-SimpleCAS/issues
  repository: https://github.com/vanstyn/Catalyst-Controller-SimpleCAS.git
version: 0.990
